### PR TITLE
update android project for latetest libfacedetection

### PR DESCRIPTION
**Pull request by dpmaycry**
update for latetest libfacedetection
simplify use for opencv4

### CODE REVIEW

**Comment by dpmaycry** [comment]
update latest libfacedetection for iOS

**Comment by fengyuentau** [comment]
Hi @dpmaycry . We have updated the model whose structure is completely different from the previous one. Would you update your code regarding android and iOS if you have time? Thanks.

**Comment by dpmaycry** [comment]
Current in the middle of other stuff. Update mobile code should be ok but may delay for a few month.

**Comment by dpmaycry** [comment]
here it is~

**Pull request merged**
